name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20] # Tu peux tester plusieurs versions de Node.js

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit & integration tests
        run: npm run test

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build   # si tu as un build
          start: npm start       # si tu dois démarrer ton serveur
          wait-on: 'http://localhost:3000' # attend que ton app soit dispo
          wait-on-timeout: 60
